apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-24-centos7
  name: httpd-24-centos7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-24-centos7
  template:
    metadata:
      labels:
        app: httpd-24-centos7
    spec:
      containers:
      - image: quay.io/centos7/httpd-24-centos7:centos7
        imagePullPolicy: IfNotPresent
        name: httpd-24-centos7